[package]
name = "spaghetto"
version = "0.0.1"
edition = "2021"

# [dependencies]
# [dev-dependencies]
# proptest = "1.0"

[dependencies.serde]
version = "1.0"
optional = true
default-features = false

[package.metadata.docs.rs]
features = ["serde"]