name: Rust

on:
  push:
    branches: [ "release/*" ]
  workflow_dispatch:
  # pull_request:
    # branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download nightly rust
      run: rustup toolchain install nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run:
        cargo +nightly miri test devec --all-features --verbose
        cargo +nightly miri test destring --all-features --verbose
        cargo test property_tests --verbose
